name: Daily NSE Update
on:
  schedule:
    # 14:12 UTC perfectly matches 7:42 PM IST
    - cron: '12 14 * * 1-5'
  workflow_dispatch: 

jobs:
  update-data:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install Dependencies
        run: pip install --upgrade --no-cache-dir requests yfinance pandas curl_cffi
        
      - name: Execute Script
        run: python automation1.py
